Repository prest/prest, pull requests merged in 2021-05, with the labels that each got.

#534 Waits for postgres service to be healthy
  docker-compose-prod.yml
  docker-compose.yml
Labels: Extra Small

#540 Fix command in tutorial
  README.md
Labels: Extra Small

#541 Fix typo in tutorial
  README.md
Labels: Extra Small

#543 migration system explanation page
  docs/migrations/_index.en.md
Labels: Small

#544 Link migration docs page on configuration
  docs/configurations/_index.en.md
Labels: Docs, Extra Small
