Repository prest/prest, pull requests merged in 2022-12, with the labels that each got.

#747 Prefer constant name.
  adapters/postgres/postgres.go
Labels: Extra Small

#751 fmt files
  adapters/postgres/errors.go
  adapters/postgres/postgres.go
  adapters/postgres/postgres_test.go
Labels: Small

#752 Pass DOCKER_COMPOSE option to make...
  Makefile
Labels: deployment/docker, product/api-server, Extra Small

#753 Basic ltree query support
  adapters/postgres/postgres.go
  adapters/postgres/postgres_test.go
  docs/api-reference/parameters.md
Labels: Extra Small
