Repository prest/prest, pull requests merged in 2023-01, with the labels that each got.

#755 test: use `T.Setenv` to set env vars in tests
  adapters/postgres/postgres_test.go
  cache/buntdb_test.go
  cache/cache_test.go
  config/config_test.go
  controllers/sql_test.go
  middlewares/config_test.go
Labels: enhancement, Large

#761 router: skip init
  router/router.go
  router/routers_test.go
Labels: Extra Small

#770 Add doc about YugabyteDB integration
  docs/integrations/yugabytedb.md
Labels: Small
